// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/loanem-backend/inventory-service/internal/service (interfaces: InstrumentService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/service/mock_instrument_service.go -package=service_mock github.com/loanem-backend/inventory-service/internal/service InstrumentService
//

// Package service_mock is a generated GoMock package.
package service_mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/loanem-backend/inventory-service/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockInstrumentService is a mock of InstrumentService interface.
type MockInstrumentService struct {
	ctrl     *gomock.Controller
	recorder *MockInstrumentServiceMockRecorder
	isgomock struct{}
}

// MockInstrumentServiceMockRecorder is the mock recorder for MockInstrumentService.
type MockInstrumentServiceMockRecorder struct {
	mock *MockInstrumentService
}

// NewMockInstrumentService creates a new mock instance.
func NewMockInstrumentService(ctrl *gomock.Controller) *MockInstrumentService {
	mock := &MockInstrumentService{ctrl: ctrl}
	mock.recorder = &MockInstrumentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstrumentService) EXPECT() *MockInstrumentServiceMockRecorder {
	return m.recorder
}

// AddInstrument mocks base method.
func (m *MockInstrumentService) AddInstrument(ctx context.Context, name string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInstrument", ctx, name)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddInstrument indicates an expected call of AddInstrument.
func (mr *MockInstrumentServiceMockRecorder) AddInstrument(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInstrument", reflect.TypeOf((*MockInstrumentService)(nil).AddInstrument), ctx, name)
}

// GetAllInstruments mocks base method.
func (m *MockInstrumentService) GetAllInstruments(ctx context.Context) ([]*entity.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInstruments", ctx)
	ret0, _ := ret[0].([]*entity.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInstruments indicates an expected call of GetAllInstruments.
func (mr *MockInstrumentServiceMockRecorder) GetAllInstruments(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInstruments", reflect.TypeOf((*MockInstrumentService)(nil).GetAllInstruments), ctx)
}

// RemoveInstrument mocks base method.
func (m *MockInstrumentService) RemoveInstrument(ctx context.Context, instrumentID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveInstrument", ctx, instrumentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveInstrument indicates an expected call of RemoveInstrument.
func (mr *MockInstrumentServiceMockRecorder) RemoveInstrument(ctx, instrumentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveInstrument", reflect.TypeOf((*MockInstrumentService)(nil).RemoveInstrument), ctx, instrumentID)
}

// SetInstrumentPicture mocks base method.
func (m *MockInstrumentService) SetInstrumentPicture(ctx context.Context, instrument *entity.Instrument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInstrumentPicture", ctx, instrument)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInstrumentPicture indicates an expected call of SetInstrumentPicture.
func (mr *MockInstrumentServiceMockRecorder) SetInstrumentPicture(ctx, instrument any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInstrumentPicture", reflect.TypeOf((*MockInstrumentService)(nil).SetInstrumentPicture), ctx, instrument)
}
