// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/loanem-backend/inventory-service/internal/service (interfaces: ToolkitService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/service/mock_toolkit_service.go -package=service_mock github.com/loanem-backend/inventory-service/internal/service ToolkitService
//

// Package service_mock is a generated GoMock package.
package service_mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/loanem-backend/inventory-service/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockToolkitService is a mock of ToolkitService interface.
type MockToolkitService struct {
	ctrl     *gomock.Controller
	recorder *MockToolkitServiceMockRecorder
	isgomock struct{}
}

// MockToolkitServiceMockRecorder is the mock recorder for MockToolkitService.
type MockToolkitServiceMockRecorder struct {
	mock *MockToolkitService
}

// NewMockToolkitService creates a new mock instance.
func NewMockToolkitService(ctrl *gomock.Controller) *MockToolkitService {
	mock := &MockToolkitService{ctrl: ctrl}
	mock.recorder = &MockToolkitServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolkitService) EXPECT() *MockToolkitServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockToolkitService) Create(ctx context.Context, t *entity.Toolkit) (int16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(int16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockToolkitServiceMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockToolkitService)(nil).Create), ctx, t)
}

// GetAll mocks base method.
func (m *MockToolkitService) GetAll(ctx context.Context) ([]*entity.Toolkit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*entity.Toolkit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockToolkitServiceMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockToolkitService)(nil).GetAll), ctx)
}

// GetWithInstruments mocks base method.
func (m *MockToolkitService) GetWithInstruments(ctx context.Context) ([]*entity.Toolkit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithInstruments", ctx)
	ret0, _ := ret[0].([]*entity.Toolkit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithInstruments indicates an expected call of GetWithInstruments.
func (mr *MockToolkitServiceMockRecorder) GetWithInstruments(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithInstruments", reflect.TypeOf((*MockToolkitService)(nil).GetWithInstruments), ctx)
}
