version: '3.8'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: inventory-service
  #   restart: unless-stopped
  #   ports:
  #     - "${APP_PORT}:${APP_PORT}"
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   networks:
  #     - backend-network

  # postgres:
  #   image: postgres:15.6-alpine
  #   container_name: postgres-db
  #   restart: unless-stopped
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASS}
  #     POSTGRES_DB: ${DB_NAME}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - backend-network

  migrate:
    image: migrate/migrate
    profiles: ["manual"]
    entrypoint: ["migrate", "create", "-ext", "sql", "-dir", "/migrations"]
    volumes:
      - ./infra/database/migrations:/migrations

  sqlc:
    image: sqlc/sqlc:1.27.0
    working_dir: /app
    volumes:
      - ./:/app
    command: ["generate"]

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge