// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: instrument.sql

package sqlc

import (
	"context"
)

const insertInstrument = `-- name: InsertInstrument :one
INSERT INTO instruments (name)
VALUES ($1)
RETURNING id
`

func (q *Queries) InsertInstrument(ctx context.Context, name string) (int16, error) {
	row := q.db.QueryRow(ctx, insertInstrument, name)
	var id int16
	err := row.Scan(&id)
	return id, err
}
