// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Instrument struct {
	ID        int16
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type ReplCourse struct {
	ID        int32
	Name      string
	Year      int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Toolkit struct {
	ID              int16
	KitName         string
	CourseID        pgtype.Int4
	TotalCount      int32
	OutOfOrderCount int32
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}
