// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: toolkit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertToolkit = `-- name: InsertToolkit :one
INSERT INTO toolkits (kit_name, total_count)
VALUES ($1, $2)
RETURNING id
`

type InsertToolkitParams struct {
	KitName    string
	TotalCount int32
}

func (q *Queries) InsertToolkit(ctx context.Context, arg InsertToolkitParams) (int16, error) {
	row := q.db.QueryRow(ctx, insertToolkit, arg.KitName, arg.TotalCount)
	var id int16
	err := row.Scan(&id)
	return id, err
}

const updateToolkitCourseID = `-- name: UpdateToolkitCourseID :exec
UPDATE toolkits
SET
    course_id = $1,
    updated_at = $2
WHERE id = $3
`

type UpdateToolkitCourseIDParams struct {
	CourseID  pgtype.Int4
	UpdatedAt pgtype.Timestamp
	ID        int16
}

func (q *Queries) UpdateToolkitCourseID(ctx context.Context, arg UpdateToolkitCourseIDParams) error {
	_, err := q.db.Exec(ctx, updateToolkitCourseID, arg.CourseID, arg.UpdatedAt, arg.ID)
	return err
}
